### ISSUE TITLE
Mismatch in the documentation regarding the xml-out parameter

### ISSUE THREAD

**Issue by philtaf** [threeal/gcovr-action#214]
There is a mismatch between the documentation and the actual label that needs to be added to use the xml-out input parameter.

The documentation indicates: 
[Output XML Report](https://github.com/threeal/gcovr-action?tab=readme-ov-file#output-xml-report)

```
- name: Generate a code coverage report
  uses: threeal/gcovr-action@v1.0.0
  with:
    xml-out: coverage.xml
```

When it appears that the xml-out parameter is included in the ["xml-out"](https://github.com/threeal/gcovr-action/tags)  tagged source, so the documentation should read:
```
- name: Generate Code Coverage Report
  uses: threeal/gcovr-action@xml-out
  with:
    xml-out: ./coverage.xml
```
